# Module: **NumPy**
# In this module about **NumPy**, we will cover the four main uses of the **NumPy framework**:

# **1. Create**
Learn how to create arrays and perform basic array operations.

# **2. Read**
Understand how to read and access array elements efficiently.

# **3. Update**
Discover methods to update and modify array contents.

# **4. Delete**
Explore techniques for deleting elements or entire arrays.

In [1]:
!pip install numpy             # Since this work has been done on Google Colab,
                               # it was not necessary to install the numpy since it is already installed in default.

In [2]:
import numpy as np              # Imports the numpy framewrok.

# **1. Creation**



In [32]:
data = np.random.rand(2, 3, 4)  # Details: '2' = number of raw groups, '3' = number of lines in each raw group and '4' = number of colums
zeroes = np.zeros((2, 3, 4))
full = np.full((2, 2, 2), 7)
ones =  np.ones((2, 2, 2))

In [41]:
data

array([[[0.09720237, 0.57855517, 0.32851135, 0.09045753],
        [0.15621137, 0.3009563 , 0.99364617, 0.09373161],
        [0.00721174, 0.86046265, 0.42262414, 0.38922245]],

       [[0.77621116, 0.142538  , 0.78021992, 0.03084569],
        [0.83679078, 0.35809691, 0.25145479, 0.69068056],
        [0.13731619, 0.46913334, 0.3344226 , 0.15116951]]])

In [33]:
zeroes

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [7]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [8]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

**How to create a numpy array**

In [17]:
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])         # Use the 'array' method.

In [18]:
type(my_array)

numpy.ndarray

In [19]:
my_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **2. Reading**

**Attributes**

In [22]:
_shape = data.shape
_type = data.dtype
_size = data.size

In [23]:
_shape            # As we can see in the result bellow, 'shape' method returns the contain of the array.

(2, 3, 4)

In [24]:
_type             # While 'dtype' method returns the type of the data of the array.

dtype('float64')

In [27]:
_size             # As we can see in the result bellow, 'size' method returns the number of items in the array.

24

**Slicing**

In [47]:
first_data = data[0]                # Returns the first raw group.
from_zero_to_2 = data[0][0:2]       # Returns the first two raws of the first raw group.
my_reverse = data[-1]               # Returns the last raw group.
single_value_first = data[0][0][0]        # Returns the first element of the first raw of the raw group.
single_value_last = data[-1][-1][0]       # Returns the first element of last raw of the last raw group.

In [40]:
first_data

array([[0.09720237, 0.57855517, 0.32851135, 0.09045753],
       [0.15621137, 0.3009563 , 0.99364617, 0.09373161],
       [0.00721174, 0.86046265, 0.42262414, 0.38922245]])

In [44]:
from_zero_to_2

array([[0.09720237, 0.57855517, 0.32851135, 0.09045753],
       [0.15621137, 0.3009563 , 0.99364617, 0.09373161]])

In [46]:
my_reverse

array([[0.77621116, 0.142538  , 0.78021992, 0.03084569],
       [0.83679078, 0.35809691, 0.25145479, 0.69068056],
       [0.13731619, 0.46913334, 0.3344226 , 0.15116951]])

In [48]:
single_value_first

0.09720236702736362

In [49]:
single_value_last

0.13731619028171982

# **3. Update**

**NB:** *Most of lists' methods works with numpy arrays, so do not hesitate to try them as well.*

***Let's first create news numpy arrays***

In [50]:
list_1 = np.random.rand(5)      # This form (a, b, c) of the numpy array is conserve with now, (a = 1, b = 5, c = 1)
list_2 = np.random.rand(3)      # Indem here to with (a = 1, b = 3, c = 1)

***Now let's see their normal output.***

In [51]:
list_1

array([0.56769321, 0.54626043, 0.41200047, 0.55389933, 0.11123296])

In [52]:
list_2

array([0.03127962, 0.05969581, 0.42130166])

# **Basic Maths**

**NB:** *operands could not be broadcast together with shapes (5,) (3,).*

Therefore, let's first rewrite our arrays.

In [59]:
list_1 = np.random.rand(5)
list_2 = np.random.rand(5)

**Let's see again their normal outputs**

In [60]:
list_1

array([0.52483584, 0.88243043, 0.80330277, 0.92018639, 0.57960254])

In [61]:
list_2

array([0.52345927, 0.5017687 , 0.33429878, 0.32729083, 0.15176571])

**Calculations**

In [63]:
add_list = np.add(list_1, list_2)
substract_list = np.subtract(list_1, list_2)
multiply_list = np.multiply(list_1, list_2)
divid_list = np.divide(list_1, list_2)
dot = np.dot(list_1, list_2)

**Results**

In [64]:
add_list

array([1.04829511, 1.38419912, 1.13760155, 1.24747722, 0.73136825])

In [65]:
substract_list

array([0.00137657, 0.38066173, 0.469004  , 0.59289557, 0.42783682])

In [66]:
multiply_list

array([0.27473019, 0.44277597, 0.26854313, 0.30116857, 0.08796379])

In [67]:
divid_list

array([1.00262976, 1.75863986, 2.4029486 , 2.81152514, 3.81906115])

In [68]:
dot

1.3751816451637797

# **Statistical Functions**

*Let's first enter the calculations*

In [86]:
sqrt =  np.sqrt(25)
ab = np.abs(-5)
power = np.power(5, 2)
log = np.log(5)
expo = np.exp([2, 3]) # e(2) and e(7)
min_list_1 = np.min(list_1)
max_list_1 = np.max(list_1)

*Now, let's look at the different results.*

In [72]:
sqrt

5.0

In [73]:
ab

5

In [74]:
power

25

In [77]:
log

1.6094379124341003

In [78]:
expo

array([ 7.3890561 , 20.08553692])

In [83]:
min_list_1

0.5248358412183715

In [87]:
max_list_1

0.9201863949784175

# **4. Delete**

***Let's first visualize again our 'data' array.***

In [88]:
data

array([[[0.09720237, 0.57855517, 0.32851135, 0.09045753],
        [0.15621137, 0.3009563 , 0.99364617, 0.09373161],
        [0.00721174, 0.86046265, 0.42262414, 0.38922245]],

       [[0.77621116, 0.142538  , 0.78021992, 0.03084569],
        [0.83679078, 0.35809691, 0.25145479, 0.69068056],
        [0.13731619, 0.46913334, 0.3344226 , 0.15116951]]])

***Now, let's say, we want to delete the first raw of each raw group.***

In [89]:
np.delete(data, 0, axis=1)

array([[[0.15621137, 0.3009563 , 0.99364617, 0.09373161],
        [0.00721174, 0.86046265, 0.42262414, 0.38922245]],

       [[0.83679078, 0.35809691, 0.25145479, 0.69068056],
        [0.13731619, 0.46913334, 0.3344226 , 0.15116951]]])

***Now, let's say, we want to save the array.***

In [ ]:
np.save("array_name", data)